steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/my-hugo-site', '.']

  # - name: 'gcr.io/cloud-builders/docker'
  #   args: ['run', '--rm', '-v', '/workspace/public:/public', 'gcr.io/$PROJECT_ID/my-hugo-site', '/public']

  - name: 'gcr.io/cloud-builders/gsutil'
    args: ['-m', 'cp', '-r', '/workspace/public/*', 'gs://www.spokeneagle.com']
options:
  logging: CLOUD_LOGGING_ONLY
