steps:
  - name: 'gcr.io/cloud-builders/git'
    args: ['clone', '--depth=1', 'https://github.com/zaarzetlite/zaarzetlite.github.io.git']

  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        VERSION=0.88.1
        wget -O /tmp/hugo.tar.gz https://github.com/gohugoio/hugo/releases/download/v$VERSION/hugo_extended_${VERSION}_Linux-64bit.tar.gz
        tar -xvf /tmp/hugo.tar.gz -C /tmp/
        mv /tmp/hugo /usr/local/bin/
        
  - name: 'gcr.io/cloud-builders/hugo'
    args: ['--source', 'zaarzetlite', '--destination', 'public']

  # Additional steps for copying the generated HTML files to your hosting resources
  # Modify the destination path as per your hosting setup
  - name: 'gcr.io/cloud-builders/gsutil'
    args: ['cp', '-r', 'public', 'gs://www.spokeneagle.com']

options:
  logging: CLOUD_LOGGING_ONLY

# Optional: Specify any substitutions or variables you need
substitutions:
  _HUGO_VERSION: '0.88.1'
  _MY_VARIABLE: 'my-value'

# Optional: Set specific tags or branches to trigger the build
# In this example, it triggers for pushes to the "main" branch
# and tags starting with "v" (e.g., "v1.0", "v2.1", etc.)
tags:
  - 'main'
  - 'v0'
  - 'v1'
  - 'v2'
  # Add more specific tags as needed, or use a wider range if appropriate
